(defun php-current-public-method-name ()
  (interactive)
  (search-backward "public function")
  (search-forward " function ")
  (setq method-name-start (point))
  (search-forward "(")
  (left-char)
  (setq method-name-end (point))
  (string-trim (buffer-substring-no-properties method-name-start method-name-end))
  )
